# Form implementation generated from reading ui file 'midikeylinker/views/main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 650)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("midikeylinker/views/icon/midi.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    \n"
"}\n"
"QAction {\n"
"    background-color:  #2D2C2C; \n"
"}\n"
"QFrame {\n"
"    background-color:  #2D2C2C; \n"
"}\n"
"QListWidget {\n"
"    background-color:  #444343;\n"
"}\n"
"QLineEdit {\n"
"    background-color:  #444343;\n"
"    color: white;\n"
"}\n"
"QTableView{\n"
"    background-color:  #444343;\n"
"}\n"
"QMenu {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:  #2D2C2C; \n"
"}\n"
"QMenuBar {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:  #2D2C2C; \n"
"}\n"
"QPushButton#linkButton { \n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: gray;\n"
"    font: bold 14px; \n"
"    padding: 6px;\n"
"    color: \"orange\";\n"
"}\n"
"QStatusBar {\n"
"    background-color:  #2D2C2C; \n"
"    color: \"orange\";\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 350))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 190))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(parent=self.frame_2)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 190))
        self.listWidget.setStyleSheet("")
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.listWidget.setAutoScrollMargin(0)
        self.listWidget.setTextElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.listWidget.setFlow(QtWidgets.QListView.Flow.LeftToRight)
        self.listWidget.setUniformItemSizes(True)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(20, 180))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 190))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 190))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.checkBox = QtWidgets.QCheckBox(parent=self.frame_4)
        self.checkBox.setGeometry(QtCore.QRect(10, 60, 85, 20))
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setEnabled(False)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.tv_midimessages = QtWidgets.QTableView(parent=self.frame_3)
        self.tv_midimessages.setGeometry(QtCore.QRect(10, 10, 611, 145))
        self.tv_midimessages.setMaximumSize(QtCore.QSize(16777215, 145))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tv_midimessages.setFont(font)
        self.tv_midimessages.setStyleSheet("")
        self.tv_midimessages.setAutoScrollMargin(16)
        self.tv_midimessages.setTextElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.tv_midimessages.setShowGrid(False)
        self.tv_midimessages.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.tv_midimessages.setObjectName("tv_midimessages")
        self.tv_midimessages.horizontalHeader().setVisible(True)
        self.tv_midimessages.horizontalHeader().setHighlightSections(True)
        self.tv_midimessages.horizontalHeader().setStretchLastSection(True)
        self.tv_midimessages.verticalHeader().setVisible(False)
        self.tv_midimessages.verticalHeader().setHighlightSections(True)
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(780, 10, 31, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("midikeylinker/views/icon/play-circle.svg"))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(640, 70, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        self.frame_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_5.setStatusTip("")
        self.frame_5.setStyleSheet("QMainWindow {\n"
"    \n"
"}\n"
"QAction {\n"
"    background-color:  #2D2C2C; \n"
"}\n"
"QFrame {\n"
"    background-color:  #2D2C2C; \n"
"}\n"
"QListWidget {\n"
"    background-color:  #444343;\n"
"}\n"
"QLineEdit {\n"
"    background-color:  #444343;\n"
"    color: white;\n"
"}\n"
"QTableView{\n"
"    background-color:  #444343;\n"
"}\n"
"QMenu {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:  #2D2C2C; \n"
"}\n"
"QMenuBar {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:  #2D2C2C; \n"
"}\n"
"QPushButton#linkButton { \n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: gray;\n"
"    font: bold 14px; \n"
"    padding: 6px;\n"
"    color: \"orange\";\n"
"}\n"
"QStatusBar {\n"
"    background-color:  #2D2C2C; \n"
"    color: \"orange\";\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.linkButton = QtWidgets.QPushButton(parent=self.frame_5)
        self.linkButton.setGeometry(QtCore.QRect(695, 190, 121, 32))
        self.linkButton.setStyleSheet("")
        self.linkButton.setCheckable(True)
        self.linkButton.setObjectName("linkButton")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 350, 100))
        self.label_2.setMaximumSize(QtCore.QSize(350, 100))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("midikeylinker/views/icon/computer-keyboard.svg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_5)
        self.lineEdit.setGeometry(QtCore.QRect(640, 50, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(790, 10, 31, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("midikeylinker/views/icon/play-circle.svg"))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.frame_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 850, 24))
        self.menuBar.setStyleSheet("")
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(parent=self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuExperimental = QtWidgets.QMenu(parent=self.menuBar)
        self.menuExperimental.setToolTipsVisible(True)
        self.menuExperimental.setObjectName("menuExperimental")
        self.menuHelp = QtWidgets.QMenu(parent=self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuMIDI_KeyLinker = QtWidgets.QMenu(parent=self.menuBar)
        self.menuMIDI_KeyLinker.setObjectName("menuMIDI_KeyLinker")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.openFileAction = QtGui.QAction(parent=MainWindow)
        self.openFileAction.setCheckable(False)
        self.openFileAction.setObjectName("openFileAction")
        self.saveAction = QtGui.QAction(parent=MainWindow)
        self.saveAction.setObjectName("saveAction")
        self.saveAsAction = QtGui.QAction(parent=MainWindow)
        self.saveAsAction.setObjectName("saveAsAction")
        self.actionmessages = QtGui.QAction(parent=MainWindow)
        self.actionmessages.setObjectName("actionmessages")
        self.actiondevices = QtGui.QAction(parent=MainWindow)
        self.actiondevices.setObjectName("actiondevices")
        self.actionDoc = QtGui.QAction(parent=MainWindow)
        self.actionDoc.setObjectName("actionDoc")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPreferences = QtGui.QAction(parent=MainWindow)
        self.actionPreferences.setCheckable(False)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionQuit = QtGui.QAction(parent=MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.openFileAction)
        self.menuFile.addAction(self.saveAction)
        self.menuFile.addAction(self.saveAsAction)
        self.menuFile.addSeparator()
        self.menuExperimental.addAction(self.actionmessages)
        self.menuExperimental.addSeparator()
        self.menuExperimental.addAction(self.actiondevices)
        self.menuHelp.addAction(self.actionDoc)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuMIDI_KeyLinker.addAction(self.actionPreferences)
        self.menuMIDI_KeyLinker.addSeparator()
        self.menuMIDI_KeyLinker.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuMIDI_KeyLinker.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuExperimental.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setToolTip(_translate("MainWindow", "See MIDI device details"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.linkButton.setText(_translate("MainWindow", "Link"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuExperimental.setStatusTip(_translate("MainWindow", "Experimental options"))
        self.menuExperimental.setTitle(_translate("MainWindow", "Experimental"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuMIDI_KeyLinker.setTitle(_translate("MainWindow", "MIDI KeyLinker"))
        self.openFileAction.setText(_translate("MainWindow", "Open"))
        self.openFileAction.setToolTip(_translate("MainWindow", "Open"))
        self.openFileAction.setStatusTip(_translate("MainWindow", "Open settings"))
        self.saveAction.setText(_translate("MainWindow", "Save"))
        self.saveAction.setStatusTip(_translate("MainWindow", "Save settings"))
        self.saveAsAction.setText(_translate("MainWindow", "Save as ..."))
        self.saveAsAction.setStatusTip(_translate("MainWindow", "Save file as ..."))
        self.actionmessages.setText(_translate("MainWindow", "Messages"))
        self.actionmessages.setStatusTip(_translate("MainWindow", "Midi messages"))
        self.actiondevices.setText(_translate("MainWindow", "Devices"))
        self.actiondevices.setStatusTip(_translate("MainWindow", "Midi Devices"))
        self.actionDoc.setText(_translate("MainWindow", "Index"))
        self.actionDoc.setToolTip(_translate("MainWindow", "Index"))
        self.actionDoc.setStatusTip(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setStatusTip(_translate("MainWindow", "About"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionPreferences.setStatusTip(_translate("MainWindow", "Preferences"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setStatusTip(_translate("MainWindow", "Exit application"))
